name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Generate Static Map with API Key
      run: |
        # 네이버 클라우드 Maps API로 정적 지도 이미지 생성
        # API 키를 환경변수에서 가져와서 이미지 URL 생성
        CLIENT_ID="${{ secrets.NAVER_MAPS_CLIENT_ID }}"
        CLIENT_SECRET="${{ secrets.NAVER_MAPS_CLIENT_SECRET }}"
        
        # 정적 지도 이미지 URL을 HTML에 삽입
        sed -i "s|https://maps.apigw.ntruss.com/map-static/v2/staticmap?center=126.8354,37.5589&level=15&w=400&h=300&scale=1&markers=126.8354,37.5589|https://maps.apigw.ntruss.com/map-static/v2/staticmap?center=126.8354,37.5589&level=15&w=400&h=300&scale=1&markers=126.8354,37.5589&key=${CLIENT_ID}|g" index.html
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
